version: '1.0.{build}'
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  - cmd: echo hello
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Tokenizer/Tokenizer.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./Tokenizer/Tokenizer.csproj
after_build:
  # For once the build has completed
#artifacts:
# - path: '\src\bin\Debug\netcoreapp1.1\publish'
#   name: WebSite
#   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Tokenizer.Tests/Tokenizer.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Tokenizer.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off
