version: '2.1.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Tokenizer/Tokenizer.csproj --verbosity m
build_script:
  # output will be in ./Tokenizer/Tokenizer/bin/Release/{framework}
  - cmd: dotnet build ./Tokenizer/Tokenizer.csproj -c Release -f netstandard2.0
  - cmd: dotnet build ./Tokenizer/Tokenizer.csproj -c Release -f net452
  - cmd: dotnet pack ./Tokenizer/Tokenizer.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
- path: .\**\*.nupkg
  name: Package
  type: NuGetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Tokenizer.Tests/Tokenizer.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Tokenizer.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: YsZCVu8lLcQlDxg3pHUU7MPCZrC4ri69VpwmQecgfxxV54BUpoAvYjSOgrc0CzMj
  on:
    branch: master
    appveyor_repo_tag: true